curl --location 'http://127.0.0.1:1337/api/digimetal-navigations' \
--header 'Content-Type: application/json' \
--data '{
  "data": {
    "name": "default",
    "headerLogoPath": "/logos/lob/abcd.svg",
    "mobileHeaderLogoPath": "/logos/lob/abcd.svg",
    "navTabs": [
      {
        "order": 1,
        "tabId": "invest",
        "label": "Invest",
        "menuItems": [
          {
            "order": 1,
            "itemId": "mutual-funds",
            "title": "Mutual Funds",
            "description": "For long term wealth",
            "iconPath": "/assets/mobile-nav/icon-mutual-funds.png",
            "navigateToUrl": "https://www.adityabirlacapital.com/abcd/mutual-funds",
            "hasDetailContent": false
          }
        ],
        "promoBanners": [
          {
            "order": 1,
            "backgroundColor": "#fff4ce",
            "preTitle": "THE PROMISE THAT LASTS",
            "preTitleColor": "#845800",
            "title": "Secure your future with life insurance that protects what matters most",
            "ctaText": "Get Covered",
            "ctaUrl": "https://www.adityabirlacapital.com/insurance/life-insurance",
            "imagePath": "/assets/mobile-nav/promo-gold.png",
            "imageAlt": "Gold bars"
          }
        ],
        "footerBanner": {
          "qrCodePath": "/assets/transaction-promo-banner/qrcode-abcd-app.webp",
          "text": "Scan here to start investing on the ABCD app",
          "appStoreButtonsPath": "/assets/nav-header/app-store-buttons.svg",
          "appStoreButtonsAlt": "App Store buttons"
        }
      }
    ],
    "mobileFooterBanner": {
      "text": "Manage your investments on the ABCD app",
      "appStoreIconPath": "/assets/mobile-nav/apple-store-icon.svg",
      "appStoreLabel": "App Store",
      "appStoreUrl": "https://apps.apple.com/in/app/abcd-one-app-for-all-needs/id1520780055",
      "playStoreIconPath": "/assets/mobile-nav/play-store-icon.svg",
      "playStoreLabel": "Play Store",
      "playStoreUrl": "https://play.google.com/store/apps/details?id=com.abcd.singleapp"
    }
  }
}'